name: Docker Image Build - Intel drivers

on:
  push:
    branches: [ master, dev*, test*, experimental ]
  pull_request:
    branches: [ master, dev*, test*, experimental ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        chmod a+w output/
        ls -alth
        ./build_intel.sh

    - name: Info on Docker images
      run: |
        docker -v
        docker images

    - name: Run the Docker image
      run: |
        echo "Skipping actual run of Intel Docker image, due to segfaults observed on GitHub runners"
        #sudo apt-get update && sudo apt-get install -y x11-xserver-utils # for xhost
        #./run.sh

    - name: Info on generated files
      run: |
        ls -alth
