name: Docker Image Build and Run

on:
  push:
    branches: [ master, dev*, test* ]
  pull_request:
    branches: [ master, dev*, test* ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Build the Docker image
      run: |
        chmod a+w output/
        ls -alth
        ./build.sh
        
    - name: Info on Docker images
      run: |
        docker -v
        docker images
    - name: Run the Docker image
      run: |
        ./run.sh -d 150 # long test...
    - name: Info on generated files
      run: |
        ls -alth
        ls -alth output
        ls -alth output/*
        more output/*/report.json 

        find output/C2_FW*/cut*mp4 -maxdepth 1 -size +300k | grep -q .  # Fails if not found or too small 

