name: Docker Image Quick Run

on:
  push:
    branches: [ master, dev*, test*, experimental ]
  pull_request:
    branches: [ master, dev*, test*, experimental ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Build the Docker image
      run: |
        chmod a+w output/
        ls -alth
        ./build.sh
    - name: Info on Docker images
      run: |
        docker -v
        docker images
    - name: Run the Docker image
      run: |
        sudo apt-get update && sudo apt-get install -y x11-xserver-utils # for xhost
        ./run-quick.sh
    - name: Info on generated files
      run: |
        ls -alth
        ls -alth output
        ls -alth output/*
