name: Docker Image Build and Run

on:
  push:
    branches: [ master, dev*, experimental, test* ]
  pull_request:
    branches: [ master, dev*, experimental, test* ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Build the Docker image
      run: |
        chmod a+w output/
        ls -alth
        ./build.sh

    - name: Info on Docker images
      run: |
        docker -v
        docker images

    - name: Run the Docker image with the default falling cube demo from sibernetic 
      run: |
        #### sudo apt-get update && sudo apt-get install -y x11-xserver-utils # for xhost
        ./run.sh -d 20 -c demo1

    - name: Run the Docker image with a worm simulation - no c302
      run: |
        ./stop.sh
        ./run.sh -d 10 -n 

    - name: Run the Docker image with a worm simulation
      run: |
        ./stop.sh
        ./run.sh -d 150 # temp longer simulation for testing

    - name: Info on generated files
      run: |
        ls -alth
        ls -alth output
        ls -alth output/*
        more output/*/report.json 

        find output/C2_FW*/cut*mp4 -maxdepth 1 -size +300k | grep -q .  # Fails if not found or too small 

